/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Systick Using Busy wait */

//#include "main.h"
//
//int main(void)
//{
//	*((volatile u32*)(0x40023830))=0xFFFFFFF;
//	Gpio_enuInit();
//	Systick_enuInit();
//
//
//
//
//	for(;;){
//
//		Gpio_enuSetPinChannelAtomic(GPIO_PING13);
//		Systick_enuSetBusyWait(2000000);
//
//
//		Gpio_enuClearPinChannelAtomic(GPIO_PING13);
//		Systick_enuSetBusyWait(2000000);
//
//
//
//	}
//}


////////////////////////////////////////////////////////////////////////////////////////
#include "main.h"

Rcc_ConfigType rcc={
		.address_pll_cfg = NULL,
		.address_pll_sai_cfg = NULL,
		.adress_pll_i2s_cfg = NULL,
		.rcc_ahb_select_prescaler = RCC_AHB_SELECT_PRESCALER_SYSTEM_CLK_NO_DIV,
		.rcc_apb1_select_prescaler = RCC_APB1_SELECT_PRESCALER_AHB_NO_DIV,
		.rcc_apb2_select_prescaler = RCC_APB2_SELECT_PRESCALER_AHB_NO_DIV,
		.rcc_hse_on_or_off = RCC_ON,
		.rcc_hsi_on_or_off = RCC_ON,
		.rcc_pllSAI_on_or_off = RCC_OFF,
		.rcc_pllSAI_on_or_off = RCC_OFF,
		.rcc_pll_on_or_off = RCC_OFF,
		.rcc_sysmte_clk_soruce = RCC_SYSTEM_CLK_HSE_INDEX
};

int main(void)
{
	Rcc_enuInit(&rcc);

	Rcc_enuInitMCO2(RCC_MCO2_PIN_SELECT_HSE_CLK,RCC_MCO2_PIN_SELECT_PRESCALER_NO_DIV);

	Gpio_enuEnableClockGIPOx(GPIO_PORTC);
	Gpio_enuEnableClockGIPOx(GPIO_PORTG);



	Systick_enuInit();
	Gpio_enuInit();

	for(;;){

				Gpio_enuSetPinChannelAtomic(GPIO_PING13);
				Systick_enuSetBusyWait(2000000);


				Gpio_enuClearPinChannelAtomic(GPIO_PING13);
				Systick_enuSetBusyWait(2000000);


	}
}
