/**************************************************************************/
/* Filename						: GPIO_config.h                            */
/* Author  	    				: Muhammad Ammar                          */
/* Date 						: Nov 6, 2023  	           	 	         	 */ 
/* Version 	 					: V01                                     */
/* MicroController  			: STM32429 								   */
/* Trainee At					: NTI (4 Months)						  */
/* Instructor					: Mahmoud Embabi						  */
/**************************************************************************/


#ifndef GPIO_GPIO_CONFIG_H_
#define GPIO_GPIO_CONFIG_H_



/********************************** Includes *********************************************/


/********************************** Macros Declarations *******************************/


/*	             _ARGU_1       	         	 | 		    _ARGU_2 	   ||       _ARGU_3 			 || 		       _ARGU_4		 ||
 * 		    GPIO_NO_PULL_UP_NO_PULL_DOWN     | 	    GPIO_LOW_SPEED     || 	  GPIO_OUTPUT_PUSH_PULL  ||	 	       GPIO_MODE_INPUT   ||
 * 			GPIO_PULL_UP 					 | 		GPIO_MEDIUM_SPEED  ||     GPIO_OUTPUT_OPEN_DRAIN ||   		   GPIO_MODE_OUTPUT  ||
 * 			GPIO_PULL_DOWN  				 | 		GPIO_HIGH_SPEED    ||               			 ||				 GPIO_MODE_AF	 ||
 * 				                    		 |    GPIO_VHIGH_SPEED	   ||     						 ||		    	GPIO_MODE_ANALOG ||
 */


/* GPIO PORT A */

#define GPIO_u8PinChannel0_PINA0					GPIO_NO_PULL_UP_NO_PULL_DOWN, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL,  GPIO_MODE_INPUT
#define GPIO_u8PinChannel1_PINA1					GPIO_PULL_UP, GPIO_MEDIUM_SPEED , GPIO_OUTPUT_OPEN_DRAIN , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel2_PINA2					GPIO_PULL_DOWN, GPIO_HIGH_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_AF
#define GPIO_u8PinChannel3_PINA3					GPIO_PULL_UP, GPIO_VHIGH_SPEED , GPIO_OUTPUT_OPEN_DRAIN , GPIO_MODE_ANALOG
#define GPIO_u8PinChannel4_PINA4					GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel5_PINA5					GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel6_PINA6					GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel7_PINA7					GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel8_PINA8					GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel9_PINA9					GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel10_PINA10				    GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel11_PINA11				    GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel12_PINA12			      	GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT

// Don't Change next, using in JTAG, look at page 1686
#define GPIO_u8PinChannel13_PINA13					GPIO_NO_PULL_UP_NO_PULL_DOWN, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_AF
#define GPIO_u8PinChannel14_PINA14					GPIO_NO_PULL_UP_NO_PULL_DOWN, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_AF
#define GPIO_u8PinChannel15_PINA15					GPIO_NO_PULL_UP_NO_PULL_DOWN, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_AF

/* GPIO PORT B *//* GPIO PORT B */


#define GPIO_u8PinChannel16_PINB0				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel17_PINB1				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel18_PINB2				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel19_PINB3				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel20_PINB4				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel21_PINB5				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel22_PINB6				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel23_PINB7				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel24_PINB8				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel25_PINB9				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel26_PINB10				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel27_PINB11				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel28_PINB12				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel29_PINB13				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel30_PINB14				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel31_PINB15				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_AF

/* GPIO PORT C */

#define GPIO_u8PinChannel32_PINC0				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel33_PINC1				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel34_PINC2				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel35_PINC3				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel36_PINC4				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel37_PINC5				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel38_PINC6				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel39_PINC7				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel40_PINC8				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT

#define GPIO_u8PinChannel41_PINC9				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_AF // MCO2
#define GPIO_u8PinChannel42_PINC10				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel43_PINC11				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel44_PINC12				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel45_PINC13				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel46_PINC14				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel47_PINC15				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT

/* GPIO PORT D */

#define GPIO_u8PinChannel48_PIND0				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel49_PIND1				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel50_PIND2				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel51_PIND3				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel52_PIND4				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel53_PIND5				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel54_PIND6				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel55_PIND7				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel56_PIND8				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel57_PIND9				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel58_PIND10				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel59_PIND11				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel60_PIND12				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel61_PIND13				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel62_PIND14				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel63_PIND15				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT

/* GPIO PORT E */

#define GPIO_u8PinChannel64_PINE0				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel65_PINE1				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel66_PINE2				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel67_PINE3				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel68_PINE4				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel69_PINE5				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel70_PINE6				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel71_PINE7				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel72_PINE8				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel73_PINE9				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel74_PINE10				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel75_PINE11				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel76_PINE12				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel77_PINE13				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel78_PINE14				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel79_PINE15				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT

/* GPIO PORT F */

#define GPIO_u8PinChannel80_PINF0				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel81_PINF1				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel82_PINF2				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel83_PINF3				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel84_PINF4				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel85_PINF5				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel86_PINF6				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel87_PINF7				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel88_PINF8				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel89_PINF9				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel90_PINF10				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel91_PINF11				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel92_PINF12				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel93_PINF13				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel94_PINF14				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel95_PINF15				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT

/* GPIO PORT G */

#define GPIO_u8PinChannel96_PING0				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel97_PING1				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel98_PING2				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel99_PING3				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel100_PING4				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel101_PING5				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel102_PING6				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel103_PING7				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel104_PING8				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel105_PING9				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel106_PING10				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel107_PING11				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel108_PING12				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel109_PING13				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel110_PING14				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel111_PING15				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT

///* GPIO PORT H */

#define GPIO_u8PinChannel112_PINH0				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel113_PINH1				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel114_PINH2				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel115_PINH3				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel116_PINH4				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel117_PINH5				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel118_PINH6				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel119_PINH7				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel120_PINH8				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel121_PINH9				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel122_PINH10				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel123_PINH11				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel124_PINH12				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel125_PINH13				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel126_PINH14				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
#define GPIO_u8PinChannel127_PINH15				GPIO_PULL_UP, GPIO_LOW_SPEED , GPIO_OUTPUT_PUSH_PULL , GPIO_MODE_OUTPUT
//
///* GPIO PORT I */
//
//#define GPIO_u8PinChannel128_PINI0
//#define GPIO_u8PinChannel129_PINI1
//#define GPIO_u8PinChannel130_PINI2
//#define GPIO_u8PinChannel131_PINI3
//#define GPIO_u8PinChannel132_PINI4
//#define GPIO_u8PinChannel133_PINI5
//#define GPIO_u8PinChannel134_PINI6
//#define GPIO_u8PinChannel135_PINI7
//#define GPIO_u8PinChannel136_PINI8
//#define GPIO_u8PinChannel137_PINI9
//#define GPIO_u8PinChannel138_PINI10
//#define GPIO_u8PinChannel139_PINI11
//#define GPIO_u8PinChannel140_PINI12
//#define GPIO_u8PinChannel141_PINI13
//#define GPIO_u8PinChannel142_PINI14
//#define GPIO_u8PinChannel143_PINI15
//
///* GPIO PORT J */
//
//#define GPIO_u8PinChannel144_PINJ0
//#define GPIO_u8PinChannel145_PINJ1
//#define GPIO_u8PinChannel146_PINJ2
//#define GPIO_u8PinChannel147_PINJ3
//#define GPIO_u8PinChannel148_PINJ4
//#define GPIO_u8PinChannel149_PINJ5
//#define GPIO_u8PinChannel150_PINJ6
//#define GPIO_u8PinChannel151_PINJ7
//#define GPIO_u8PinChannel152_PINJ8
//#define GPIO_u8PinChannel153_PINJ9
//#define GPIO_u8PinChannel154_PINJ10
//#define GPIO_u8PinChannel155_PINJ11
//#define GPIO_u8PinChannel156_PINJ12
//#define GPIO_u8PinChannel157_PINJ13
//#define GPIO_u8PinChannel158_PINJ14
//#define GPIO_u8PinChannel159_PINJ15
//
///* GPIO PORT K */
//
//#define GPIO_u8PinChannel160_PINK0
//#define GPIO_u8PinChannel161_PINK1
//#define GPIO_u8PinChannel162_PINK2
//#define GPIO_u8PinChannel163_PINK3
//#define GPIO_u8PinChannel164_PINK4
//#define GPIO_u8PinChannel165_PINK5
//#define GPIO_u8PinChannel166_PINK6
//#define GPIO_u8PinChannel167_PINK7
//#define GPIO_u8PinChannel168_PINK8
//#define GPIO_u8PinChannel169_PINK9
//#define GPIO_u8PinChannel170_PINK10
//#define GPIO_u8PinChannel171_PINK11
//#define GPIO_u8PinChannel172_PINK12
//#define GPIO_u8PinChannel173_PINK13
//#define GPIO_u8PinChannel174_PINK14
//#define GPIO_u8PinChannel175_PINK15







/********************************** Macros Function Declarations *********************/


/********************************** Data Type Declarations ****************************/



/********************************** Software Interfaces Declarations *******************/



#endif /* GPIO_GPIO_CONFIG_H_ */
